#' Score model output predictions
#'
#' Scores model outputs with a single `output_type` against observed data.
#'
#' @param model_out_tbl Model output tibble with predictions
#' @param oracle_output Predictions that would have been generated by an oracle
#' model that knew the observed target data values in advance
#' @param metrics Character vector of scoring metrics to compute. If `NULL`
#' (the default), appropriate metrics are chosen automatically. See details
#' for more.
#' @param relative_metrics Character vector of scoring metrics for which to
#' compute relative skill scores. The `relative_metrics` should be a subset of
#' `metrics` and should only include proper scores (e.g., it should not contain
#' interval coverage metrics).  If `NULL` (the default), no relative metrics
#' will be computed.  Relative metrics are only computed if `summarize = TRUE`,
#' and require that `"model_id"` is included in `by`.
#' @param baseline String with the name of a model to use as a baseline for
#' relative skill scores. If a baseline is given, then a scaled relative skill
#' with respect to the baseline will be returned. By default (`NULL`), relative
#' skill will not be scaled with respect to a baseline model.
#' @param summarize Boolean indicator of whether summaries of forecast scores
#' should be computed. Defaults to `TRUE`.
#' @param by Character vector naming columns to summarize by. For example,
#' specifying `by = "model_id"` (the default) will compute average scores for
#' each model.
#' @param output_type_id_order For ordinal variables in pmf format, this is a
#' vector of levels for pmf forecasts, in increasing order of the levels. The
#' order of the values for the output_type_id can be found by referencing the
#' hub's tasks.json configuration file. For all output types other than pmf,
#' this is ignored.
#' @param compound_taskid_set When `NULL` (the default), sample forecasts are
#' scored marginally (each modeling task scored independently). When a character
#' vector of task ID column names is provided, it sets the compound grouping:
#' the specified columns stay constant within each sample draw, while the
#' remaining task ID dimensions vary within a draw and are scored jointly
#' (using the energy score). Only applicable when
#' `output_type == "sample"`. The value of `compound_taskid_set` can be found
#' by referencing the hub's `tasks.json` configuration file.
#' @param transform A function to apply as a scale transformation to both
#'   predictions and observations before scoring. Common choices include
#'   \code{\link[scoringutils]{log_shift}} (recommended for log transformation
#'   as it handles zeros via an offset parameter), \code{sqrt}, or
#'   \code{log1p}. Avoid using \code{log} directly if data may contain zeros.
#'   If `NULL` (the default), no transformation is applied. Only supported for
#'   quantile, mean, and median output types.
#' @param transform_append Logical. If `FALSE` (the default), scores are
#'   computed only on the transformed scale. If `TRUE`, scores are computed on
#'   both original and transformed scales, with a `scale` column distinguishing
#'   them. Ignored if `transform = NULL`.
#' @param transform_label A character string label for the transformation
#'   (e.g., "log"). If `NULL` (the default), the label is auto-generated from
#'   the function name (e.g., "log_shift" for `scoringutils::log_shift`).
#'   Required when using an anonymous transform function. Ignored if
#'   `transform = NULL`. Note: the label only appears in output when
#'   `transform_append = TRUE`, where it distinguishes transformed rows
#'   (labeled with this value) from original rows (labeled "natural") in the
#'   `scale` column.
#' @param ... Additional arguments passed to the `transform` function. For
#'   example, allows use of the `offset` and `base` arguments of
#'   [scoringutils::log_shift()]. Ignored if `transform = NULL`.
#'
#' @details
#' See the hubverse documentation for the expected format of the
#' [oracle output data](https://docs.hubverse.io/en/latest/user-guide/target-data.html#oracle-output).
#'
#' Default metrics are provided by the `scoringutils` package. You can select
#' metrics by passing in a character vector of metric names to the `metrics`
#' argument.
#'
#' The following metrics can be selected (all are used by default) for the
#' different `output_type`s:
#'
#' **Quantile forecasts:** (`output_type == "quantile"`)
#' `r ex <- c("interval_coverage_50", "interval_coverage_90")`
#' `r .metrics_list(scoringutils::example_quantile, exclude = ex)`
#' - "interval_coverage_XX": interval coverage at the "XX" level. For example,
#' "interval_coverage_95" is the 95% interval coverage rate, which would be calculated
#' based on quantiles at the probability levels 0.025 and 0.975.
#'
#' See [scoringutils::get_metrics.forecast_quantile] for details.
#'
#' **Nominal forecasts:** (`output_type == "pmf"` and `output_type_id_order` is `NULL`)
#'
#' `r .metrics_list(scoringutils::example_nominal)`
#'
#' See [scoringutils::get_metrics.forecast_nominal] for details.
#'
#' **Ordinal forecasts:** (`output_type == "pmf"` and `output_type_id_order` is a vector)
#'
#' `r .metrics_list(scoringutils::example_ordinal)`
#'
#' See [scoringutils::get_metrics.forecast_ordinal] for details.
#'
#' **Median forecasts:** (`output_type == "median"`)
#'
#' - ae_point: absolute error of the point forecast (recommended for the median, see Gneiting (2011))
#'
#' See [scoringutils::get_metrics.forecast_point] for details.
#'
#' **Mean forecasts:** (`output_type == "mean"`)
#' - `se_point`: squared error of the point forecast (recommended for the mean, see Gneiting (2011))
#'
#' **Sample forecasts (marginal):** (`output_type == "sample"`, `compound_taskid_set = NULL`)
#'
#' `r .metrics_list(scoringutils::example_sample_continuous)`
#'
#' Note: `log_score` uses kernel density estimation, which may not be
#' appropriate for integer-valued forecasts. `scoringutils` will warn when
#' this is detected.
#'
#' See [scoringutils::get_metrics.forecast_sample] for details.
#'
#' **Sample forecasts (compound):** (`output_type == "sample"`, `compound_taskid_set` provided)
#'
#' `r .metrics_list(scoringutils::example_multivariate_sample)`
#'
#' See [scoringutils::get_metrics.forecast_sample_multivariate] for details.
#' The output includes a `.mv_group_id` column assigned by `scoringutils` to
#' identify the multivariate groups used for scoring (equivalent to the
#' `compound_idx` concept in the
#' [hubverse sample output type documentation
#' ](https://docs.hubverse.io/en/latest/user-guide/sample-output-type.html)).
#' Correct scoring depends on providing the right `compound_taskid_set` from
#' the hub's `tasks.json` configuration. If the specified grouping does not
#' match the actual dependence structure of the submitted samples (e.g.,
#' because some models submitted coarser samples than configured),
#' `.mv_group_id` may not correspond to the original sample draws as
#' indicated by their `output_type_id` values.
#'
#' See [scoringutils::add_relative_skill] for details on relative skill scores.
#'
#' @examplesIf requireNamespace("hubExamples", quietly = TRUE)
#' # compute WIS and interval coverage rates at 80% and 90% levels based on
#' # quantile forecasts, summarized by the mean score for each model
#' quantile_scores <- score_model_out(
#'   model_out_tbl = hubExamples::forecast_outputs |>
#'     dplyr::filter(.data[["output_type"]] == "quantile"),
#'   oracle_output = hubExamples::forecast_oracle_output,
#'   metrics = c("wis", "interval_coverage_80", "interval_coverage_90"),
#'   relative_metrics = "wis",
#'   by = "model_id"
#' )
#' quantile_scores
#'
#' # compute log scores based on pmf predictions for categorical targets,
#' # summarized by the mean score for each combination of model and location.
#' # Note: if the model_out_tbl had forecasts for multiple targets using a
#' # pmf output_type with different bins, it would be necessary to score the
#' # predictions for those targets separately.
#' pmf_scores <- score_model_out(
#'   model_out_tbl = hubExamples::forecast_outputs |>
#'     dplyr::filter(.data[["output_type"]] == "pmf"),
#'   oracle_output = hubExamples::forecast_oracle_output,
#'   metrics = c("log_score", "rps"),
#'   by = c("model_id", "location", "horizon"),
#'   output_type_id_order = c("low", "moderate", "high", "very high")
#' )
#' head(pmf_scores)
#'
#' # Score sample forecasts marginally (each modeling task scored independently).
#' # Note: this data has compound structure (samples span horizons), but marginal
#' # scoring is still valid -- it evaluates each horizon independently.
#' sample_scores <- score_model_out(
#'   model_out_tbl = hubExamples::forecast_outputs |>
#'     dplyr::filter(.data[["output_type"]] == "sample"),
#'   oracle_output = hubExamples::forecast_oracle_output,
#'   metrics = "crps",
#'   by = "model_id"
#' )
#' sample_scores
#'
#' # Score compound sample forecasts jointly using the energy score.
#' # compound_taskid_set specifies which task IDs stay constant within
#' # a sample group -- here, each sample draw spans all horizons for a
#' # given reference_date and location (i.e., a trajectory over time).
#' compound_scores <- score_model_out(
#'   model_out_tbl = hubExamples::forecast_outputs |>
#'     dplyr::filter(.data[["output_type"]] == "sample"),
#'   oracle_output = hubExamples::forecast_oracle_output,
#'   compound_taskid_set = c("reference_date", "location"),
#'   by = "model_id"
#' )
#' compound_scores
#'
#' @return A data.table with scores
#'
#' @references
#' Gneiting, Tilmann. 2011. "Making and Evaluating Point Forecasts." Journal of the
#' American Statistical Association 106 (494): 746–62. <doi: 10.1198/jasa.2011.r10138>.
#'
#' @export
score_model_out <- function(
  model_out_tbl,
  oracle_output,
  metrics = NULL,
  relative_metrics = NULL,
  baseline = NULL,
  summarize = TRUE,
  by = "model_id",
  output_type_id_order = NULL,
  compound_taskid_set = NULL,
  transform = NULL,
  transform_append = FALSE,
  transform_label = NULL,
  ...
) {
  # check that model_out_tbl has a single output_type that is supported by this package
  # also, retrieve that output_type
  output_type <- validate_output_type(model_out_tbl)

  if (!is.null(compound_taskid_set) && output_type != "sample") {
    cli::cli_abort(
      "{.arg compound_taskid_set} is only applicable to sample output types,
      but {.arg model_out_tbl} has output type {.val {output_type}}."
    )
  }

  # Validate transformation parameters and capture expression for label inference
  transform_expr <- rlang::enexpr(transform)
  validate_transform(transform, transform_label, output_type)
  if (summarize) {
    # Note: The call to scoringutils::add_relative_skill below performs validation of `baseline`
    validate_relative_metrics(relative_metrics, metrics, by)
  }

  # assemble data for scoringutils
  su_data <- switch(
    output_type,
    quantile = transform_quantile_model_out(model_out_tbl, oracle_output),
    pmf = transform_pmf_model_out(
      model_out_tbl,
      oracle_output,
      output_type_id_order
    ),
    mean = transform_point_model_out(model_out_tbl, oracle_output, output_type),
    median = transform_point_model_out(
      model_out_tbl,
      oracle_output,
      output_type
    ),
    sample = transform_sample_model_out(
      model_out_tbl,
      oracle_output,
      compound_taskid_set
    ),
    NULL # default, should not happen because of the validation above
  )

  # Apply scale transformation if requested
  if (!is.null(transform)) {
    # Use the captured expression for label inference (e.g., "log_shift")
    label <- get_transform_label(transform_expr, transform_label)
    su_data <- scoringutils::transform_forecasts(
      su_data,
      fun = transform,
      append = transform_append,
      label = label,
      ...
    )
  }

  # get/validate the scoring metrics
  metrics <- get_metrics(
    forecast = su_data,
    output_type = output_type,
    select = metrics
  )

  # compute scores
  scores <- scoringutils::score(su_data, metrics)

  # switch back to hubverse naming conventions for model name
  scores <- dplyr::rename(scores, model_id = "model")

  # if requested, summarize scores, including computation of relative metrics
  if (summarize) {
    for (metric in relative_metrics) {
      scores <- scoringutils::add_relative_skill(
        scores,
        compare = "model_id",
        by = by[by != "model_id"],
        metric = metric,
        baseline = baseline
      )
    }
    scores <- scoringutils::summarize_scores(scores = scores, by = by)
  }

  scores
}


#' Get scoring metrics
#'
#' @param forecast A scoringutils `forecast` object (see
#' [scoringutils' general information on creating a forecast object][scoringutils::as_forecast_doc_template()]
#' for details).
#' @inheritParams score_model_out
#'
#' @return a list of metric functions as required by scoringutils::score()
#'
#' @noRd
get_metrics <- function(forecast, output_type, select = NULL) {
  forecast_type <- class(forecast)[1]

  # process quantile metrics separately to allow better selection of interval
  # coverage metrics
  if (forecast_type == "forecast_quantile") {
    # split into metrics for interval coverage and others
    interval_metric_inds <- is_interval_coverage_metric(select)
    interval_metrics <- select[interval_metric_inds]
    other_metrics <- select[!interval_metric_inds]

    other_metric_fns <- scoringutils::get_metrics(
      forecast,
      select = other_metrics
    )

    # assemble interval coverage functions
    interval_metric_fns <- lapply(
      interval_metrics,
      function(metric) {
        level_str <- substr(metric, 19, nchar(metric))
        level <- suppressWarnings(as.numeric(level_str))
        if (is.na(level) || level <= 0 || level >= 100) {
          cli::cli_abort(c(
            "Invalid interval coverage level: {level_str}",
            "i" = "must be a number between 0 and 100 (exclusive)"
          ))
        }
        purrr::partial(scoringutils::interval_coverage, interval_range = level)
      }
    )
    names(interval_metric_fns) <- interval_metrics

    metric_fns <- c(other_metric_fns, interval_metric_fns)
    return(metric_fns)
  }

  # leave validation of user selection to scoringutils
  metric_fns <- scoringutils::get_metrics(forecast, select = select)
  if (output_type == "mean") {
    metric_fns <- scoringutils::select_metrics(metric_fns, "se_point")
  } else if (output_type == "median") {
    metric_fns <- scoringutils::select_metrics(metric_fns, "ae_point")
  }

  metric_fns
}


#' Determine whether metric is an interval coverage metric
#'
#' @param metrics Character vector of metric names
#' @return Logical vector indicating whether each metric is an interval coverage metric
#' @noRd
is_interval_coverage_metric <- function(metric) {
  grepl(pattern = "^interval_coverage_", metric)
}
