#' Transform quantile model output into a forecast object
#'
#' @param model_out_tbl Model output tibble with predictions
#' @param oracle_output Predictions that would have been generated by an oracle
#' model that knew the observed target data values in advance
#'
#' @return forecast_quantile
#'
#' @export
transform_quantile_model_out <- function(model_out_tbl, oracle_output) {
  model_out_tbl <- validate_model_oracle_out(model_out_tbl, oracle_output)

  task_id_cols <- get_task_id_cols(model_out_tbl)

  model_out_tbl <- model_out_tbl |>
    dplyr::filter(.data[["output_type"]] == "quantile") |>
    dplyr::mutate(output_type_id = as.numeric(.data[["output_type_id"]])) |>
    dplyr::rename(model = "model_id")

  if (c("output_type") %in% colnames(oracle_output)) {
    oracle_output <- oracle_output |>
      dplyr::filter(.data[["output_type"]] == "quantile") |>
      dplyr::select(-c("output_type", "output_type_id"))
  }

  data <- dplyr::left_join(model_out_tbl, oracle_output,
    by = task_id_cols[task_id_cols %in% colnames(oracle_output)],
    relationship = "many-to-one"
  )

  forecast_quantile <- scoringutils::as_forecast_quantile(data,
    forecast_unit = c("model", task_id_cols),
    observed = "oracle_value",
    predicted = "value",
    quantile_level = "output_type_id"
  )

  forecast_quantile
}
